name: Code Quality
run-name: ${{ github.actor }} is checking Code Quality 🔎
on:
  pull_request:
    branches:
      - main


#montar el resto de jobs según los pasos que hay en el README
#añadir los jobs que creo a las rules
jobs:
  check-linter: #hacer el jobs para la parte de Code Quality del Linter que hay en el README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the Project
        run: uv sync --all-extras --dev
        shell: bash

      - name: Run Check Linter
        run: uv run ruff check .
        shell: bash

  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the Project
        run: uv sync --all-extras --dev
        shell: bash

      - name: Format Code
        run: uv run ruff format .
        shell: bash

      - name: Run Check Formatter
        run: uv run ruff format --check .
        shell: bash

  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the Project
        run: uv sync --all-extras --dev
        shell: bash

      - name: Run Check Type Safety
        run: uv run pyright
        shell: bash

  unit-tests:
    runs-on: ubuntu-latest
    steps: #replicar lo que hago en la terminal, buscar "uv github actions"
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the Project
        run: uv sync --all-extras --dev
        shell: bash

      - name: Run Unit Tests
        run: uv run pytest
        shell: bash
